In [85]:
a = [3,6,8,10,1,2,1]

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

# print(quicksort(a))
# print(set(quicksort(a)))
# s = 'hello'
# print(s.capitalize())
# print(s.upper())
# print(s.rjust(20))
# print(s.ljust(20))
# print(s.center(20))
# print(s.replace('l', 'ppp'))
# print(s.ljust(20).strip())

# animals = ['cat', 'dog', 'monkey']
# for idx, animal in enumerate(animals):
#     print('#%d: %s' % (idx + 1, animal))

# d = {'person': 2, 'cat': 4, 'spider': 8}
#  python3 中 items是将字典转换为列表，列表的元素是键值对组成的元组
#  python2中itemiters是将字典转换为可迭代对象，返回的是键值对组成的可迭代对象
# for animal, legs in d.items():     
#     print('A %s has %d legs' % (animal, legs))


import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
# v = np.array([1, 0, 1])
# y = np.empty_like(x)
# print('x = ', x, sep='\n')
# print('y = ', y, sep='\n')

# m = np.zeros(x.shape)
# print(m.shape)
# print(v.shape)
# m = m + v
# vv = np.tile(x, (4, 1))
# print(vv)
# print(vv.shape)
# print(x)
# y = np.array(range(4)).reshape(4,1)   # [0, 1, 2, 3].T
# z = np.array(range(3))  # [0, 1, 2]
# y + z

# from scipy.misc import imread, imsave, imshow, imresize

# img = imread('2.jpg')
# print(img.shape, img.dtype)
# img_tinted = img * [1, 0.95, 0.9]
# print(img_tinted.shape, img_tinted.dtype)
# img_tinted = imresize(img_tinted, (300, 300))
# import matplotlib.pyplot as plt
# plt.imshow(np.float64(img_tinted))   
# # 不能直接用imshow()函数
# plt.show()
# imsave('cat_tinted.jpg', img_tinted)


from scipy.spatial.distance import cdist
a = np.array(range(24)).reshape(4,6)
b = np.array(range(4, 10)).reshape(1,6)
d = cdist(a, b, 'euclidean')
print(d)

[[ 9.79795897]
 [ 4.89897949]
 [19.59591794]
 [34.2928564 ]]


# 用list实现矩阵乘法

In [105]:

class MyArray():
    def __init__(self):
        pass
    
    def matrixMultiply(self, A, B):
        # 获取A的行数和列数
        A_row, A_col = A.shape
        # 获取B的行数和列数
        B_row, B_col = B.shape
        # 不能运算情况的判断
        if(A_col != B_row):
            raise ValueError('输入元素不匹配')

        # 最终的矩阵
        result = []

        # zip 解包后是转置后的元组，强转成list, 存入result中，相当于转置
        BT = [list(row) for row in zip(*B)]
        print(b, BT, A,sep='\n')
        # 开始做乘积运算
        for A_index in range(A_row):
            # 用于记录新矩阵的每行元素
            rowItem = []
            for B_index in range(len(BT)):
                # num 用于累加
                num = 0
                for Br in range(len(BT[B_index])):
                    num +=  A[A_index][Br] * BT[B_index][Br]
                # 累加完成后，将数据存入新矩阵的行中
                rowItem.append(num)
            result.append(rowItem)
        return result
        
a = np.array(range(1, 7)).reshape(2, 3)
b = np.array(range(2, 8)).reshape(3, 2)
#print(a)
#print(b)
cls = MyArray()
print(cls.matrixMultiply(a,b))\


[[2 3]
 [4 5]
 [6 7]]
[[2, 4, 6], [3, 5, 7]]
[[1 2 3]
 [4 5 6]]
[[28, 34], [64, 79]]


In [116]:
def MatMul(A, B):
    A_row, A_col = A.shape
    B_row, B_col = B.shape
    if A_col != B_row:
        raise ValueError("input array subject to m*n * n*m. Please try again.")
    # 计算矩阵B的转置
    BT = [list(row) for row in zip(*B)]
    print('A=', A, 'BT=', BT, sep='\n')
    result = [] # 最终结果
    for A_idx in range(len(A)):
        row_items = []  # 记录行
        for BT_idx in range(len(BT)):
            num = 0
            for BT_row_idx in range(len(BT[BT_idx])):
                num += A[A_idx][BT_row_idx] * BT[BT_idx][BT_row_idx]
            row_items.append(num)
        result.append(row_items)
    
    return result
    
a = np.array(range(1, 7)).reshape(2, 3)
b = np.array(range(2, 8)).reshape(3, 2)
c = MatMul(a,b)
print(c)

A=
[[1 2 3]
 [4 5 6]]
BT=
[[2, 4, 6], [3, 5, 7]]
[[28, 34], [64, 79]]
